# Run the ESPHome 2026.9.0 CLI (Docker) on growell-display.yaml.
#   .\tools\esphome.ps1 config    validate the YAML
#   .\tools\esphome.ps1 compile   build the firmware (first run downloads the ESP-IDF toolchain)
param(
    [Parameter(Mandatory = $true)]
    [ValidateSet('config', 'compile')]
    [string]$Command
)
$root = Split-Path -Parent $PSScriptRoot
# ESPHome needs a secrets.yaml next to the config. The real secrets live in ESPHome Builder;
# for local validation we generate throwaway random values once (the file is git-ignored).
$secrets = Join-Path $root 'secrets.yaml'
if (-not (Test-Path $secrets)) {
    $chars = [char[]]'abcdefghijklmnopqrstuvwxyz0123456789'
    $rand = { param($n) -join (1..$n | ForEach-Object { $chars | Get-Random }) }
    $key = New-Object byte[] 32
    [Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($key)
    @(
        '# Local throwaway values for validating/compiling only (generated by tools/esphome.ps1, git-ignored).'
        "wifi_ssid: `"local-$(& $rand 8)`""
        "wifi_password: `"$(& $rand 16)`""
        "growell_api_key: `"$([Convert]::ToBase64String($key))`""
        'ha_url: "http://192.168.1.10:8123"'
        "ha_token: `"$(& $rand 32)`""
    ) | Set-Content -Encoding ascii $secrets
}
# /cache keeps toolchains between runs; /build keeps the build tree off the slow Windows mount.
docker run --rm `
    -v "${root}:/config" `
    -v growell-esphome-cache:/cache `
    -v growell-esphome-build:/build `
    ghcr.io/esphome/esphome:2026.9.0 $Command growell-display.yaml
exit $LASTEXITCODE
